# Generated by Django 4.1.5 on 2023-05-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
